#!/bin/sh

# build the ports.txt file from the ports subsets

X_DESTFILE="ports-full.txt"

echo "# Autogenerated by p.sh, do not edit!" > ${X_DESTFILE}
echo "#" >> ${X_DESTFILE}

for i in ports/ports-*.txt ; do
	echo "# from ${i}" >> ${X_DESTFILE}
	echo "#" >> ${X_DESTFILE}
	cat ${i} >> ${X_DESTFILE}
	echo "" >> ${X_DESTFILE}
done

echo "# End" >> ${X_DESTFILE}
